name = "StatisticalRethinkingDHMC"
authors = ["goedman"]

[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
DynamicHMC = "bbc10e6e-7c05-544b-b16e-64fede858acb"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
StatisticalRethinking = "2d09df54-9d0f-5258-8220-54c2a3d4fbee"
TransformVariables = "84d833dd-6860-57f9-a1a7-6da5db126cff"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
julia = "1.5"
